### ISSUE TITLE
Colors.toHexString doesn't work with black

### ISSUE THREAD

**Issue by hermanbergwerf** [google/vector_math.dart#174]
`Colors.toHexString(new Vector4(0.0, 0.0, 0.0, 1.0))` gives `0` instead of `000000`.

**Comment by hermanbergwerf** [comment]
Green doesn't work either. It gives `ff00`. I think the output should be left padded with zeros.

**Comment by Fox32** [comment]
Yeah, the problem is that the function converts the whole integer to a hex string, not each component on its own like you would expect it for usage with css (. Each component that has to be padded with 0, one option would be to omit the padding if all components have only one digit.

I can take a look later today. Better unit tests would have caught that problem earlier ;)
