### ISSUE TITLE
Matrix4.translate crashes when supplied with an integer

### ISSUE THREAD

**Issue by Norbert515** [google/vector_math.dart#212]
When translating a matrix:
```
Matrix4.identity()..translate(0, 100)
```
it throws 
```
The method 'toDouble' was called on null.
Receiver: null
Tried calling: toDouble()
```

it traces back to:[https://github.com/google/vector_math.dart/blob/master/lib/src/vector_math_64/matrix4.dart#L682](https://github.com/google/vector_math.dart/blob/master/lib/src/vector_math_64/matrix4.dart#L682)

This is because the type of the first parameter is used to determine how to use the parameters.

Two problems:

- Ints should probably be allowed too (and if not, an appropriate error message should be thrown)
- Dart auto converts ints which are supposed to be doubles, but because the first parameter is dynamic therefore it does not.

Possible solutions:
```
    } else if (x is double) {
      tx = x;
      ty = y;
      tz = z;
    }
``` 
check for `x is num` instead or add an expicit `x is int` check.

Happy to submit a PR if that helps.

**Comment by deven98** [comment]
Submitted PR for fix

**Comment by johnmccutchan** [comment]
We should make translate less flexible and require that 'x' be a double.

In general we want to avoid checks / casts in vector_math code so that we don't slow down well behaved programs.

**Comment by deven98** [comment]
@johnmccutchan What was the original purpose of keeping x dynamic? Also, should I rewrite the PR and make the argument for x an explicit double instead?

**Comment by deven98** [comment]
@johnmccutchan wouldn't that break cases where x is supplied a vector in existing code? Adding an int check wouldn't increase the number of checks except where x is specifically an integer.

**Comment by johnmccutchan** [comment]
Is anyone actually using the version where x is a vector? Why are all callers of translate paying the price for type checks?

**Comment by deven98** [comment]
@johnmccutchan Can you confirm you want to remove all checks and make translate and similar functions accept ONLY a double as x? In that case, I'll rewrite my PR when you confirm.

**Comment by johnmccutchan** [comment]
Yes

**Comment by johnmccutchan** [comment]
There is also leftTranslate, scale, scaled, that follow the same dynamic type dispatch which has poor performance.

**Comment by deven98** [comment]
Got it, will ping here when new PR is submitted.

**Comment by deven98** [comment]
@johnmccutchan Converted dynamic types for the four functions into double. PR updated.

**Comment by rakudrama** [comment]
@johnmccutchan How can we tell if anyone is using these APIs with a Vector3 or Vector4? I don't see any internal uses but I worry about breaking external users.

I agree it is a poor design to 'dispatch' dynamic arguments to get an effect similar to overloading in Java to C#. However, I am worried that it will break existing code or it will become difficult to do things that could be done before. I don't see with the current change how to get the same effect as `m.translate(Vector4(0.1, 0.2, 0.3, 0.4))`.

If we want to support things that used to be possible, we could split each method into three methods which call a private method:
```dart
void translate(double x, [double y = 0.0, double z = 0.0]) {
  _translate(x, y, z, 1.0);
}
void _translate(double tx, double ty, double tz, double tw) {
   ... code using tx/ty/tz/tw
}
void translateByVector3(Vector3 v)  {
  _translate(v.x, v.y, v.z, 1.0);
}
void translateByVector4(Vector4 v) {
  _translate(v.x, v.y, v.z, v.w);
}
```
This structure would be efficient since the compilers will often inline the simple public forwarding method.

If we go ahead with a change like the current PR we need:
- Tests of new APIs and verify that tests exist for the xyz case.
- Ensure 32- and 64- bit versions are in sync. This is best done by working on the `vector_math/` version and running `tool/generate_vector_math_64.dart` to generate the `vector_math_64/` directory.
- An entry in the `changelog.md` describing the changes, and how to migrate existing code that uses Vector3 and Vector4.
- This would be a big enough change to increment the version number. We do this with every change that affects the API so users can pin the old version that they know works with their app.

**Comment by deven98** [comment]
@rakudrama Understood. Editing PR for change now.

**Comment by deven98** [comment]
@rakudrama @johnmccutchan Updated PR to split functions into double, Vector3 and Vector4 types. Added tests for all new functions and added entry to changelog. Also updated version to 2.1.0-dev.

**Comment by Binozo** [comment]
Issue still exists
